### ISSUE TITLE
front end hide non applicable pages for user type

### ISSUE THREAD

**Issue by jff97** [jff97/cs341GroupProject#39]
- all page gating should be scalable and easily changeable. Each type of user should be able to have one or more pages available to that role. This should be a easy configuration in the future. 
- Normal users should only see the book appointment section.
- Service providers should only see the create appointment section currently with opportunity to add more sections to their allowed list.
- Admin's should have access to admin dashboard, booking but not create appointment

**Comment by czagrzebski** [comment]
This is done on a per-feature basis and I don't know if we need an issue for this. Correct me if I'm wrong.
